apiVersion: nginx.example.org/v1alpha1
kind: Nginx
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx-sample
    app.kubernetes.io/part-of: k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s
  name: nginx-sample
spec:
  # TODO(user): Add fields here
