apiVersion: nginx.example.org/v1alpha1
kind: Nginx
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx-sample
    app.kubernetes.io/part-of: k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s
  name: nginx-sample

spec:
  image: nginx:stable-alpine # if unspecified, defaults to "nginx:latest"
  port: 80
  replicas: 2
  healthcheckPath: /healthz  # if unspecified, doesn't set readiness probes on nginx pods
  resources:                 # if unspecified, defaults to unlimited
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 32Mi
  config:
    kind: Inline
    value: |-
      events {}

      http {
        default_type text/plain;

        server {
          listen 8080 default_server;

          location / {
            return 302 '/greeting?name=world';
          }

          location = /greeting {
            set $name ${arg_name};

            if ($name = '') {
              set $name 'anonymous';
            }

            return 200 'Hello, ${name}!\n';
          }

          location = /healthz {
            access_log off;
            return 200 'WORKING\n';
          }
        }
      }
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaled-nginx
spec:
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 85
  scaleTargetRef:
    apiVersion: nginx.example.org/v1alpha1
    kind: Nginx
    name: my-autoscaled-nginx